address `check()`-only treesitter error
previously saw:

```
Error: Input must point to a valid tree sitter type.

     Backtrace:
         ▆
      1. ├─testthat::expect_success(expect_r_code("x <- 1")) at test-expect.R:2:3
      2. │ └─testthat::capture_expectation(expr)
      3. │   └─base::tryCatch(...)
      4. │     └─base (local) tryCatchList(expr, classes, parentenv, handlers)
      5. │       └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
      6. │         └─base (local) doTryCatch(return(expr), name, parentenv, handler)
      7. └─evalthat::expect_r_code("x <- 1")
      8.   └─treesitter::parser_parse(...)
```

seems that the object doesn't serialize properly, maybe?